# This Trigger subscribes to the Broker and filters events based on the type and badwordfilter attribute.
# Those comments that contain insults are filtered out by the badwordfilter attribute and they will be redirected to the event-display Service.
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: reply-trigger
spec:
  broker: broker
  filter:
    attributes:
      type: moderated-comment
      badwordfilter: bad
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display

