apiVersion: flows.knative.dev/v1
kind: Sequence
metadata:
  name: sequence
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
  steps:
    - ref:
        apiVersion: v1
        kind: Service
        name: bad-word-filter
    - ref:
        apiVersion: v1
        kind: Service
        name: sentiment-raw
  reply:
    ref:
      kind: Broker
      apiVersion: eventing.knative.dev/v1
      name: broker